/*********************************************
* Author: Leah Buechley
* Filename: pin_macros.h
* Chip: general
* Created: 11/2/2005
* Modified: summer 2006
* Purpose: to make controlling pins on AVR microcontrollers
* easy & intuitive
*/

//set pins as input 
#define a0Input() DDRA &= ~_BV(PA0)
#define a1Input() DDRA &= ~_BV(PA1)
#define a2Input() DDRA &= ~_BV(PA2)
#define a3Input() DDRA &= ~_BV(PA3)
#define a4Input() DDRA &= ~_BV(PA4)
#define a5Input() DDRA &= ~_BV(PA5)
#define a6Input() DDRA &= ~_BV(PA6)
#define a7Input() DDRA &= ~_BV(PA7)

#define b0Input() DDRB &= ~_BV(PB0)
#define b1Input() DDRB &= ~_BV(PB1)
#define b2Input() DDRB &= ~_BV(PB2)
#define b3Input() DDRB &= ~_BV(PB3)
#define b4Input() DDRB &= ~_BV(PB4)
#define b5Input() DDRB &= ~_BV(PB5)
#define b6Input() DDRB &= ~_BV(PB6)
#define b7Input() DDRB &= ~_BV(PB7)

#define c0Input() DDRC &= ~_BV(PC0)
#define c1Input() DDRC &= ~_BV(PC1)
#define c2Input() DDRC &= ~_BV(PC2)
#define c3Input() DDRC &= ~_BV(PC3)
#define c4Input() DDRC &= ~_BV(PC4)
#define c5Input() DDRC &= ~_BV(PC5)
#define c6Input() DDRC &= ~_BV(PC6)
#define c7Input() DDRC &= ~_BV(PC7)

#define d0Input() DDRD &= ~_BV(PD0)
#define d1Input() DDRD &= ~_BV(PD1)
#define d2Input() DDRD &= ~_BV(PD2)
#define d3Input() DDRD &= ~_BV(PD3)
#define d4Input() DDRD &= ~_BV(PD4)
#define d5Input() DDRD &= ~_BV(PD5)
#define d6Input() DDRD &= ~_BV(PD6)
#define d7Input() DDRD &= ~_BV(PD7)

#define e0Input() DDRE &= ~_BV(PE0)
#define e1Input() DDRE &= ~_BV(PE1)
#define e2Input() DDRE &= ~_BV(PE2)
#define e3Input() DDRE &= ~_BV(PE3)
#define e4Input() DDRE &= ~_BV(PE4)
#define e5Input() DDRE &= ~_BV(PE5)
#define e6Input() DDRE &= ~_BV(PE6)
#define e7Input() DDRE &= ~_BV(PE7)

//set pins as output
#define a0Output() DDRA|= _BV(PA0)
#define a1Output() DDRA|= _BV(PA1)
#define a2Output() DDRA|= _BV(PA2)
#define a3Output() DDRA|= _BV(PA3)
#define a4Output() DDRA|= _BV(PA4)
#define a5Output() DDRA|= _BV(PA5)
#define a6Output() DDRA|= _BV(PA6)
#define a7Output() DDRA|= _BV(PA7)

#define b0Output() DDRB|= _BV(PB0)
#define b1Output() DDRB|= _BV(PB1)
#define b2Output() DDRB|= _BV(PB2)
#define b3Output() DDRB|= _BV(PB3)
#define b4Output() DDRB|= _BV(PB4)
#define b5Output() DDRB|= _BV(PB5)
#define b6Output() DDRB|= _BV(PB6)
#define b7Output() DDRB|= _BV(PB7)

#define c0Output() DDRC|= _BV(PC0)
#define c1Output() DDRC|= _BV(PC1)
#define c2Output() DDRC|= _BV(PC2)
#define c3Output() DDRC|= _BV(PC3)
#define c4Output() DDRC|= _BV(PC4)
#define c5Output() DDRC|= _BV(PC5)
#define c6Output() DDRC|= _BV(PC6)
#define c7Output() DDRC|= _BV(PC7)

#define d0Output() DDRD|= _BV(PD0)
#define d1Output() DDRD|= _BV(PD1)
#define d2Output() DDRD|= _BV(PD2)
#define d3Output() DDRD|= _BV(PD3)
#define d4Output() DDRD|= _BV(PD4)
#define d5Output() DDRD|= _BV(PD5)
#define d6Output() DDRD|= _BV(PD6)
#define d7Output() DDRD|= _BV(PD7)

#define e0Output() DDRE|= _BV(PE0)
#define e1Output() DDRE|= _BV(PE1)
#define e2Output() DDRE|= _BV(PE2)
#define e3Output() DDRE|= _BV(PE3)
#define e4Output() DDRE|= _BV(PE4)
#define e5Output() DDRE|= _BV(PE5)
#define e6Output() DDRE|= _BV(PE6)
#define e7Output() DDRE|= _BV(PE7)

//set pins high
#define a0High() PORTA|= _BV(PA0)
#define a1High() PORTA|= _BV(PA1) 
#define a2High() PORTA|= _BV(PA2)
#define a3High() PORTA|= _BV(PA3)
#define a4High() PORTA|= _BV(PA4)
#define a5High() PORTA|= _BV(PA5)
#define a6High() PORTA|= _BV(PA6)
#define a7High() PORTA|= _BV(PA7)

#define b0High() PORTB|= _BV(PB0)
#define b1High() PORTB|= _BV(PB1)
#define b2High() PORTB|= _BV(PB2)
#define b3High() PORTB|= _BV(PB3)
#define b4High() PORTB|= _BV(PB4)
#define b5High() PORTB|= _BV(PB5)
#define b6High() PORTB|= _BV(PB6)
#define b7High() PORTB|= _BV(PB7)

#define c0High() PORTC|= _BV(PC0)
#define c1High() PORTC|= _BV(PC1)
#define c2High() PORTC|= _BV(PC2)
#define c3High() PORTC|= _BV(PC3)
#define c4High() PORTC|= _BV(PC4)
#define c5High() PORTC|= _BV(PC5)
#define c6High() PORTC|= _BV(PC6)
#define c7High() PORTC|= _BV(PC7)

#define d0High() PORTD|= _BV(PD0)
#define d1High() PORTD|= _BV(PD1)
#define d2High() PORTD|= _BV(PD2)
#define d3High() PORTD|= _BV(PD3)
#define d4High() PORTD|= _BV(PD4)
#define d5High() PORTD|= _BV(PD5)
#define d6High() PORTD|= _BV(PD6)
#define d7High() PORTD|= _BV(PD7)

#define e0High() PORTE|= _BV(PE0)
#define e1High() PORTE|= _BV(PE1)
#define e2High() PORTE|= _BV(PE2)
#define e3High() PORTE|= _BV(PE3)
#define e4High() PORTE|= _BV(PE4)
#define e5High() PORTE|= _BV(PE5)
#define e6High() PORTE|= _BV(PE6)
#define e7High() PORTE|= _BV(PE7)

//set pins low
#define a0Low() PORTA &= ~_BV(PA0)
#define a1Low() PORTA &= ~_BV(PA1)
#define a2Low() PORTA &= ~_BV(PA2)
#define a3Low() PORTA &= ~_BV(PA3)
#define a4Low() PORTA &= ~_BV(PA4)
#define a5Low() PORTA &= ~_BV(PA5)
#define a6Low() PORTA &= ~_BV(PA6)
#define a7Low() PORTA &= ~_BV(PA7)

#define b0Low() PORTB &= ~_BV(PB0)
#define b1Low() PORTB &= ~_BV(PB1)
#define b2Low() PORTB &= ~_BV(PB2)
#define b3Low() PORTB &= ~_BV(PB3)
#define b4Low() PORTB &= ~_BV(PB4)
#define b5Low() PORTB &= ~_BV(PB5)
#define b6Low() PORTB &= ~_BV(PB6)
#define b7Low() PORTB &= ~_BV(PB7)

#define c0Low() PORTC &= ~_BV(PC0)
#define c1Low() PORTC &= ~_BV(PC1)
#define c2Low() PORTC &= ~_BV(PC2)
#define c3Low() PORTC &= ~_BV(PC3)
#define c4Low() PORTC &= ~_BV(PC4)
#define c5Low() PORTC &= ~_BV(PC5)
#define c6Low() PORTC &= ~_BV(PC6)
#define c7Low() PORTC &= ~_BV(PC7)

#define d0Low() PORTD &= ~_BV(PD0)
#define d1Low() PORTD &= ~_BV(PD1)
#define d2Low() PORTD &= ~_BV(PD2)
#define d3Low() PORTD &= ~_BV(PD3)
#define d4Low() PORTD &= ~_BV(PD4)
#define d5Low() PORTD &= ~_BV(PD5)
#define d6Low() PORTD &= ~_BV(PD6)
#define d7Low() PORTD &= ~_BV(PD7)

#define e0Low() PORTE &= ~_BV(PE0)
#define e1Low() PORTE &= ~_BV(PE1)
#define e2Low() PORTE &= ~_BV(PE2)
#define e3Low() PORTE &= ~_BV(PE3)
#define e4Low() PORTE &= ~_BV(PE4)
#define e5Low() PORTE &= ~_BV(PE5)
#define e6Low() PORTE &= ~_BV(PE6)
#define e7Low() PORTE &= ~_BV(PE7)

//digital input low check
#define a0IsLow() bit_is_clear(PINA,0)
#define a1IsLow() bit_is_clear(PINA,1)
#define a2IsLow() bit_is_clear(PINA,2)
#define a3IsLow() bit_is_clear(PINA,3)
#define a4IsLow() bit_is_clear(PINA,4)
#define a5IsLow() bit_is_clear(PINA,5)
#define a6IsLow() bit_is_clear(PINA,6)
#define a7IsLow() bit_is_clear(PINA,7)

#define b0IsLow() bit_is_clear(PINB,0)
#define b1IsLow() bit_is_clear(PINB,1)
#define b2IsLow() bit_is_clear(PINB,2)
#define b3IsLow() bit_is_clear(PINB,3)
#define b4IsLow() bit_is_clear(PINB,4)
#define b5IsLow() bit_is_clear(PINB,5)
#define b6IsLow() bit_is_clear(PINB,6)
#define b7IsLow() bit_is_clear(PINB,7)

#define c0IsLow() bit_is_clear(PINC,0)
#define c1IsLow() bit_is_clear(PINC,1)
#define c2IsLow() bit_is_clear(PINC,2)
#define c3IsLow() bit_is_clear(PINC,3)
#define c4IsLow() bit_is_clear(PINC,4)
#define c5IsLow() bit_is_clear(PINC,5)
#define c6IsLow() bit_is_clear(PINC,6)
#define c7IsLow() bit_is_clear(PINC,7)

#define d0IsLow() bit_is_clear(PIND,0)
#define d1IsLow() bit_is_clear(PIND,1)
#define d2IsLow() bit_is_clear(PIND,2)
#define d3IsLow() bit_is_clear(PIND,3)
#define d4IsLow() bit_is_clear(PIND,4)
#define d5IsLow() bit_is_clear(PIND,5)
#define d6IsLow() bit_is_clear(PIND,6)
#define d7IsLow() bit_is_clear(PIND,7)

#define e0IsLow() bit_is_clear(PINE,0)
#define e1IsLow() bit_is_clear(PINE,1)
#define e2IsLow() bit_is_clear(PINE,2)
#define e3IsLow() bit_is_clear(PINE,3)
#define e4IsLow() bit_is_clear(PINE,4)
#define e5IsLow() bit_is_clear(PINE,5)
#define e6IsLow() bit_is_clear(PINE,6)
#define e7IsLow() bit_is_clear(PINE,7)

//digital input high check
#define a0IsHigh() bit_is_set(PINA,0)
#define a1IsHigh() bit_is_set(PINA,1)
#define a2IsHigh() bit_is_set(PINA,2)
#define a3IsHigh() bit_is_set(PINA,3)
#define a4IsHigh() bit_is_set(PINA,4)
#define a5IsHigh() bit_is_set(PINA,5)
#define a6IsHigh() bit_is_set(PINA,6)
#define a7IsHigh() bit_is_set(PINA,7)

#define b0IsHigh() bit_is_set(PINB,0)
#define b1IsHigh() bit_is_set(PINB,1)
#define b2IsHigh() bit_is_set(PINB,2)
#define b3IsHigh() bit_is_set(PINB,3)
#define b4IsHigh() bit_is_set(PINB,4)
#define b5IsHigh() bit_is_set(PINB,5)
#define b6IsHigh() bit_is_set(PINB,6)
#define b7IsHigh() bit_is_set(PINB,7)

#define c0IsHigh() bit_is_set(PINC,0)
#define c1IsHigh() bit_is_set(PINC,1)
#define c2IsHigh() bit_is_set(PINC,2)
#define c3IsHigh() bit_is_set(PINC,3)
#define c4IsHigh() bit_is_set(PINC,4)
#define c5IsHigh() bit_is_set(PINC,5)
#define c6IsHigh() bit_is_set(PINC,6)
#define c7IsHigh() bit_is_set(PINC,7)

#define d0IsHigh() bit_is_set(PIND,0)
#define d1IsHigh() bit_is_set(PIND,1)
#define d2IsHigh() bit_is_set(PIND,2)
#define d3IsHigh() bit_is_set(PIND,3)
#define d4IsHigh() bit_is_set(PIND,4)
#define d5IsHigh() bit_is_set(PIND,5)
#define d6IsHigh() bit_is_set(PIND,6)
#define d7IsHigh() bit_is_set(PIND,7)

#define e0IsHigh() bit_is_set(PINE,0)
#define e1IsHigh() bit_is_set(PINE,1)
#define e2IsHigh() bit_is_set(PINE,2)
#define e3IsHigh() bit_is_set(PINE,3)
#define e4IsHigh() bit_is_set(PINE,4)
#define e5IsHigh() bit_is_set(PINE,5)
#define e6IsHigh() bit_is_set(PINE,6)
#define e7IsHigh() bit_is_set(PINE,7)
